import type { Metadata } from "next"
import { Poppins } from "next/font/google"

import "./globals.css"

import { ModalDetailGalery } from "@/components/molecules/modalDetailGalery"
import { Navbar } from "@/components/molecules/navbar"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ModalDetailGalery />
        <Navbar />
        {children}
      </body>
    </html>
  )
}
